# Generated by Django 5.1.3 on 2024-11-14 20:09

import django.db.models.deletion
import django_multitenant.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_initial'),
        ('fidelidade', '0002_initial'),
        ('filiais', '0001_initial'),
        ('produtos', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carimbo',
            name='owner',
            field=django_multitenant.fields.TenantForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AddField(
            model_name='cartaofidelidade',
            name='ambiente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenants.ambiente', verbose_name='tenant'),
        ),
        migrations.AddField(
            model_name='cartaofidelidade',
            name='cr_cliente',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cartoes_fidelidade', to='clientes.cliente', verbose_name='cliente'),
        ),
        migrations.AddField(
            model_name='cartaofidelidade',
            name='cr_filial',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cartoes_fidelidade', to='filiais.filial', verbose_name='filial'),
        ),
        migrations.AddField(
            model_name='cartaofidelidade',
            name='filial',
            field=django_multitenant.fields.TenantForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='filiais.filial', verbose_name='filial'),
        ),
        migrations.AddField(
            model_name='cartaofidelidade',
            name='owner',
            field=django_multitenant.fields.TenantForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AddField(
            model_name='carimbo',
            name='cb_cartao_fidelidade',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carimbos', to='fidelidade.cartaofidelidade', verbose_name='cartão fidelidade'),
        ),
        migrations.AddField(
            model_name='condicaopremio',
            name='ambiente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenants.ambiente', verbose_name='tenant'),
        ),
        migrations.AddField(
            model_name='condicaopremio',
            name='cn_produto',
            field=django_multitenant.fields.TenantForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='produtos.produto', verbose_name='produto'),
        ),
        migrations.AddField(
            model_name='condicaopremio',
            name='filial',
            field=django_multitenant.fields.TenantForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='filiais.filial', verbose_name='filial'),
        ),
        migrations.AddField(
            model_name='condicaopremio',
            name='owner',
            field=django_multitenant.fields.TenantForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AddField(
            model_name='cartaofidelidade',
            name='cr_condicao_premio',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cartoes_fidelidade', to='fidelidade.condicaopremio', verbose_name='condição da premio'),
        ),
        migrations.AddField(
            model_name='premio',
            name='ambiente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenants.ambiente', verbose_name='tenant'),
        ),
        migrations.AddField(
            model_name='premio',
            name='filial',
            field=django_multitenant.fields.TenantForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='filiais.filial', verbose_name='filial'),
        ),
        migrations.AddField(
            model_name='premio',
            name='owner',
            field=django_multitenant.fields.TenantForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AddField(
            model_name='cartaofidelidade',
            name='cr_premio',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cartoes_fidelidade', to='fidelidade.premio', verbose_name='prêmio'),
        ),
        migrations.AddField(
            model_name='premioitem',
            name='ambiente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenants.ambiente', verbose_name='tenant'),
        ),
        migrations.AddField(
            model_name='premioitem',
            name='filial',
            field=django_multitenant.fields.TenantForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='filiais.filial', verbose_name='filial'),
        ),
        migrations.AddField(
            model_name='premioitem',
            name='owner',
            field=django_multitenant.fields.TenantForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AddField(
            model_name='premioitem',
            name='pt_premio',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='fidelidade.premio', verbose_name='cliente'),
        ),
        migrations.AddField(
            model_name='premioitem',
            name='pt_produto',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='premios', to='produtos.produto', verbose_name='produto'),
        ),
    ]
