# Generated by Django 5.1.5 on 2025-01-31 19:36

import django.db.models.deletion
import django.db.models.manager
import django_lifecycle.mixins
import django_multitenant.fields
import django_multitenant.mixins
import django_multitenant.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assinaturas', '0002_initial'),
        ('clientes', '0002_initial'),
        ('filiais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('codigo', models.PositiveBigIntegerField(default=1, editable=False, verbose_name='código')),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='data de criação')),
                ('hora_criacao', models.TimeField(auto_now_add=True, verbose_name='hora de criação')),
                ('data_ultima_alteracao', models.DateField(auto_now=True, verbose_name='data da última alteração')),
                ('hora_ultima_alteracao', models.TimeField(auto_now=True, verbose_name='hora da última alteração')),
                ('dt_quantidade', models.PositiveSmallIntegerField(verbose_name='quantidade')),
                ('dt_observacao', models.CharField(max_length=100, verbose_name='observação')),
            ],
            options={
                'verbose_name': 'Item do Pedido',
                'verbose_name_plural': 'Itens dos Pedidos',
                'db_table': 'pedido_item',
                'ordering': ['-id'],
            },
            bases=(django_multitenant.mixins.TenantModelMixin, django_lifecycle.mixins.LifecycleModelMixin, models.Model),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('codigo', models.PositiveBigIntegerField(default=1, editable=False, verbose_name='código')),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='data de criação')),
                ('hora_criacao', models.TimeField(auto_now_add=True, verbose_name='hora de criação')),
                ('data_ultima_alteracao', models.DateField(auto_now=True, verbose_name='data da última alteração')),
                ('hora_ultima_alteracao', models.TimeField(auto_now=True, verbose_name='hora da última alteração')),
                ('dd_codigo', models.UUIDField(default=uuid.uuid4, verbose_name='código')),
                ('dd_cliente', models.CharField(blank=True, max_length=30, verbose_name='cliente')),
                ('dd_entrega', models.BooleanField(verbose_name='tem entrega')),
                ('dd_cep', models.CharField(blank=True, default='', max_length=8, verbose_name='cep')),
                ('dd_estado', models.PositiveSmallIntegerField(choices=[(0, 'Em branco'), (1, 'Rondônia'), (2, 'Acre'), (3, 'Amazonas'), (4, 'Roraima'), (5, 'Pará'), (6, 'Amapá'), (7, 'Tocantins'), (8, 'Maranhão'), (9, 'Piauí'), (10, 'Ceará'), (11, 'Rio Grande do Norte'), (12, 'Paraíba'), (13, 'Pernambuco'), (14, 'Alagoas'), (15, 'Sergipe'), (16, 'Bahia'), (17, 'Minas Gerais'), (18, 'Espírito Santo'), (19, 'Rio de Janeiro'), (20, 'São Paulo'), (21, 'Paraná'), (22, 'Santa Catarina'), (23, 'Rio Grande do Sul'), (24, 'Mato Grosso do Sul'), (25, 'Mato Grosso'), (26, 'Goiás'), (27, 'Distrito Federal'), (28, 'Exterior')], default=0, verbose_name='estado')),
                ('dd_cidade', models.CharField(blank=True, default='', max_length=50, verbose_name='cidade')),
                ('dd_bairro', models.CharField(blank=True, default='', max_length=40, verbose_name='bairro')),
                ('dd_rua', models.CharField(blank=True, default='', max_length=30, verbose_name='rua')),
                ('dd_numero', models.CharField(blank=True, default='', max_length=8, verbose_name='número')),
                ('dd_complemento', models.CharField(blank=True, default='', max_length=100, verbose_name='complemento')),
                ('assinatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='assinaturas.assinatura', verbose_name='tenant')),
                ('dd_cliente_fidelidade', django_multitenant.fields.TenantForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente', verbose_name='cliente fidelidade')),
                ('filial', django_multitenant.fields.TenantForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='filiais.filial', verbose_name='filial')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'pedido',
                'ordering': ['-id'],
            },
            bases=(django_multitenant.mixins.TenantModelMixin, django_lifecycle.mixins.LifecycleModelMixin, models.Model),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
    ]
