# Generated by Django 5.1.3 on 2024-11-14 20:09

import apps.descontos.models
import django.db.models.deletion
import django.db.models.manager
import django_multitenant.mixins
import django_multitenant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuponDesconto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('codigo', models.PositiveBigIntegerField(default=1, editable=False, verbose_name='código')),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='data de criação')),
                ('hora_criacao', models.TimeField(auto_now_add=True, verbose_name='hora de criação')),
                ('data_ultima_alteracao', models.DateField(auto_now=True, verbose_name='data da última alteração')),
                ('hora_ultima_alteracao', models.TimeField(auto_now=True, verbose_name='hora da última alteração')),
                ('cp_tipo', models.PositiveSmallIntegerField(choices=[(1, 'Porcentual'), (2, 'Valor')], verbose_name='tipo')),
                ('cp_expiracao', models.DateField(null=True, verbose_name='expiração')),
                ('cp_valor', models.FloatField(default=0, verbose_name='valor')),
                ('cp_valor_minimo', models.IntegerField(default=0, verbose_name='valor mínimo')),
                ('cp_codigo', models.CharField(default=apps.descontos.models.gerar_codigo_cupon_aleatorio, max_length=10, verbose_name='código')),
                ('cp_utilizado', models.BooleanField(default=False, verbose_name='utilizado')),
                ('ambiente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenants.ambiente', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'Cupon de Desconto',
                'verbose_name_plural': 'Cupons de Desconto',
                'db_table': 'cupom_desconto',
                'ordering': ['-id'],
            },
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
    ]
