# Generated by Django 5.1.3 on 2024-11-28 17:38

import django.db.models.deletion
import django.db.models.manager
import django_multitenant.fields
import django_multitenant.mixins
import django_multitenant.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0004_alter_cliente_cl_estado'),
        ('filiais', '0003_alter_filial_fl_estado'),
        ('mesas', '0002_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('codigo', models.PositiveBigIntegerField(default=1, editable=False, verbose_name='código')),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='data de criação')),
                ('hora_criacao', models.TimeField(auto_now_add=True, verbose_name='hora de criação')),
                ('data_ultima_alteracao', models.DateField(auto_now=True, verbose_name='data da última alteração')),
                ('hora_ultima_alteracao', models.TimeField(auto_now=True, verbose_name='hora da última alteração')),
                ('rs_cliente', models.CharField(max_length=80, verbose_name='cliente')),
                ('rs_data', models.DateField(verbose_name='data')),
                ('rs_hora', models.TimeField(verbose_name='hora')),
                ('rs_quantidade_pessoas', models.PositiveIntegerField(default=2, verbose_name='pessoas')),
                ('rs_observacao', models.TextField(blank=True, verbose_name='observação')),
                ('rs_hora_limite', models.TimeField(null=True, verbose_name='hora limite de chegada')),
                ('ambiente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenants.ambiente', verbose_name='tenant')),
                ('filial', django_multitenant.fields.TenantForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='filiais.filial', verbose_name='filial')),
                ('owner', django_multitenant.fields.TenantForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('rs_cliente_fidelidade', django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='clientes.cliente', verbose_name='Cliente')),
                ('rs_mesa', django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='mesas.mesa', verbose_name='Mesa')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'db_table': 'reserva',
                'ordering': ['-id'],
            },
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
    ]
