# Generated by Django 5.1.5 on 2025-01-31 19:36

import django.db.models.deletion
import django_multitenant.fields
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_initial'),
        ('mesas', '0002_initial'),
        ('reservas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='owner',
            field=django_multitenant.fields.TenantForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='rs_cliente_fidelidade',
            field=django_multitenant.fields.TenantForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='clientes.cliente', verbose_name='cliente fidelidade'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='rs_mesa',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='mesas.mesa', verbose_name='Mesa'),
        ),
    ]
