# Generated by Django 5.1.3 on 2024-12-09 17:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='rs_codigo',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='código da reserva'),
        ),
    ]
