# Generated by Django 5.1.4 on 2024-12-23 13:07

import django.db.models.deletion
import django_multitenant.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_cliente_cl_estado'),
        ('reservas', '0002_reserva_rs_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='rs_celular_cliente',
            field=models.CharField(blank=True, default='', max_length=11, verbose_name='cliente'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='rs_cliente_fidelidade',
            field=django_multitenant.fields.TenantForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='clientes.cliente', verbose_name='cliente fidelidade'),
        ),
    ]
