default_language_version:
    python: python3.10

exclude: ^\\.venv/

repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.7.2"
    hooks:
      - id: ruff
        args: ["--fix", "--select", "I"]  
