# Generated by Django 5.1.5 on 2025-01-31 19:36

import django.db.models.deletion
import django.db.models.manager
import django_lifecycle.mixins
import django_multitenant.fields
import django_multitenant.mixins
import django_multitenant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assinaturas', '0002_initial'),
        ('comandas', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComissaoGarcom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('codigo', models.PositiveBigIntegerField(default=1, editable=False, verbose_name='código')),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='data de criação')),
                ('hora_criacao', models.TimeField(auto_now_add=True, verbose_name='hora de criação')),
                ('data_ultima_alteracao', models.DateField(auto_now=True, verbose_name='data da última alteração')),
                ('hora_ultima_alteracao', models.TimeField(auto_now=True, verbose_name='hora da última alteração')),
                ('cg_status', models.PositiveSmallIntegerField(choices=[(1, 'Aberto'), (2, 'Efetuada'), (3, 'Estornada'), (4, 'Cancelada')], default=1, verbose_name='status')),
                ('cg_valor_total_comanda', models.FloatField(default=0, verbose_name='valor da comanda')),
                ('cg_valor', models.FloatField(default=0, verbose_name='valor')),
                ('cg_percentual', models.FloatField(default=0, verbose_name='percentual da comissão')),
                ('assinatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='assinaturas.assinatura', verbose_name='tenant')),
                ('cg_comanda', django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comandas.comanda', verbose_name='comanda')),
            ],
            options={
                'verbose_name': 'Comissão do Garçom',
                'verbose_name_plural': 'Comissões do Garçons',
                'db_table': 'comissao_garcom',
                'ordering': ['-id'],
            },
            bases=(django_multitenant.mixins.TenantModelMixin, django_lifecycle.mixins.LifecycleModelMixin, models.Model),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
    ]
