# Generated by Django 5.1.5 on 2025-02-10 20:11

import django.db.models.deletion
import django_multitenant.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_initial'),
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='vn_cliente_fidelidade',
            field=django_multitenant.fields.TenantForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente', verbose_name='cliente fidelidade'),
        ),
    ]
