# Generated by Django 5.1.5 on 2025-02-12 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filiais', '0003_rename_fl_catalogo_grupo_id_filial_fl_catalog_grupo_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filial',
            name='fl_id_back_blaze',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='id backblaze do upload'),
        ),
        migrations.AddField(
            model_name='filial',
            name='fl_path_logo',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='caminho da logo no bucket'),
        ),
        migrations.AddField(
            model_name='filial',
            name='fl_url_logo',
            field=models.URLField(blank=True, default='', verbose_name='url amigável da foto'),
        ),
    ]
