# Generated by Django 5.1.3 on 2024-11-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filiais', '0004_alter_filial_fl_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='filial',
            name='fl_merchat_id_ifood',
            field=models.CharField(blank=True, max_length=50, verbose_name='id do merchant no iFood'),
        ),
    ]
