# Generated by Django 5.1.5 on 2025-02-13 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filiais', '0004_filial_fl_id_back_blaze_filial_fl_path_logo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filial',
            old_name='fl_catalog_grupo_id',
            new_name='fl_catalog_group_id',
        ),
    ]
