# Generated by Django 5.1.5 on 2025-02-24 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filiais', '0005_rename_fl_catalog_grupo_id_filial_fl_catalog_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='filial',
            name='fl_client_id_ifood',
            field=models.UUIDField(default=None, null=True, verbose_name='clientSecret do iFood'),
        ),
        migrations.AddField(
            model_name='filial',
            name='fl_client_secret_ifood',
            field=models.UUIDField(default=None, null=True, verbose_name='clientId do iFood'),
        ),
    ]
