# Generated by Django 5.1.3 on 2024-12-14 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filiais', '0005_filial_fl_merchat_id_ifood'),
    ]

    operations = [
        migrations.AddField(
            model_name='filial',
            name='fl_catalog_id',
            field=models.UUIDField(default=None, null=True, verbose_name='id do merchant no iFood'),
        ),
        migrations.AddField(
            model_name='filial',
            name='fl_delivery_catalog_id',
            field=models.UUIDField(default=None, null=True, verbose_name='id do merchant no iFood'),
        ),
        migrations.AlterField(
            model_name='filial',
            name='fl_merchat_id_ifood',
            field=models.UUIDField(default=None, null=True, verbose_name='id do merchant no iFood'),
        ),
    ]
