# Generated by Django 5.1.3 on 2024-12-14 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filiais', '0006_filial_fl_catalog_id_filial_fl_delivery_catalog_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filial',
            name='fl_catalog_id',
            field=models.UUIDField(default=None, null=True, verbose_name='id do catálogo digital do iFood'),
        ),
        migrations.AlterField(
            model_name='filial',
            name='fl_delivery_catalog_id',
            field=models.UUIDField(default=None, null=True, verbose_name='id do catálogo de delivery do iFood'),
        ),
        migrations.AlterField(
            model_name='filial',
            name='fl_merchat_id_ifood',
            field=models.UUIDField(default=None, null=True, verbose_name='id do merchant do iFood'),
        ),
    ]
