# Generated by Django 5.1.4 on 2024-12-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filiais', '0007_alter_filial_fl_catalog_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filial',
            name='fl_hora_fim_funcionamento_domingo',
            field=models.TimeField(null=True, verbose_name='horário de encerramento no domingo'),
        ),
        migrations.AddField(
            model_name='filial',
            name='fl_hora_fim_funcionamento_quarta',
            field=models.TimeField(null=True, verbose_name='horário de encerramento na quarta-feira'),
        ),
        migrations.AddField(
            model_name='filial',
            name='fl_hora_fim_funcionamento_quinta',
            field=models.TimeField(null=True, verbose_name='horário de encerramento na quinta-feira'),
        ),
        migrations.AddField(
            model_name='filial',
            name='fl_hora_fim_funcionamento_sabado',
            field=models.TimeField(null=True, verbose_name='horário de encerramento no sabado'),
        ),
        migrations.AddField(
            model_name='filial',
            name='fl_hora_fim_funcionamento_segunda',
            field=models.TimeField(null=True, verbose_name='horário de encerramento na segunda-feira'),
        ),
        migrations.AddField(
            model_name='filial',
            name='fl_hora_fim_funcionamento_sexta',
            field=models.TimeField(null=True, verbose_name='horário de encerramento na sexta-feira'),
        ),
        migrations.AddField(
            model_name='filial',
            name='fl_hora_fim_funcionamento_terca',
            field=models.TimeField(null=True, verbose_name='horário de encerramento na terca-feira'),
        ),
        migrations.AddField(
            model_name='filial',
            name='fl_hora_inicio_funcionamento_domingo',
            field=models.TimeField(null=True, verbose_name='horário de início no domingo'),
        ),
        migrations.AddField(
            model_name='filial',
            name='fl_hora_inicio_funcionamento_quarta',
            field=models.TimeField(null=True, verbose_name='horário de início na quarta-feira'),
        ),
        migrations.AddField(
            model_name='filial',
            name='fl_hora_inicio_funcionamento_quinta',
            field=models.TimeField(null=True, verbose_name='horário de início na quinta-feira'),
        ),
        migrations.AddField(
            model_name='filial',
            name='fl_hora_inicio_funcionamento_sabado',
            field=models.TimeField(null=True, verbose_name='horário de início no sabado'),
        ),
        migrations.AddField(
            model_name='filial',
            name='fl_hora_inicio_funcionamento_segunda',
            field=models.TimeField(null=True, verbose_name='horário de início na segunda-feira'),
        ),
        migrations.AddField(
            model_name='filial',
            name='fl_hora_inicio_funcionamento_sexta',
            field=models.TimeField(null=True, verbose_name='horário de início na sexta-feira'),
        ),
        migrations.AddField(
            model_name='filial',
            name='fl_hora_inicio_funcionamento_terca',
            field=models.TimeField(null=True, verbose_name='horário de início na terca-feira'),
        ),
    ]
