# Generated by Django 5.1.4 on 2024-12-26 14:46

import django.db.models.deletion
import django_multitenant.fields
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filiais', '0008_filial_fl_hora_fim_funcionamento_domingo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='filial',
            name='owner',
            field=django_multitenant.fields.TenantForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='filiais', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
    ]
