# Generated by Django 5.1.4 on 2024-12-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filiais', '0009_alter_filial_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filial',
            old_name='fl_catalog_id',
            new_name='fl_catalogo_id',
        ),
        migrations.RemoveField(
            model_name='filial',
            name='fl_delivery_catalog_id',
        ),
        migrations.AddField(
            model_name='filial',
            name='fl_catalogo_grupo_id',
            field=models.UUIDField(default=None, null=True, verbose_name='id do grupo do catálogo do iFood'),
        ),
    ]
