# Generated by Django 5.1.5 on 2025-04-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracao',
            name='cf_descricao',
            field=models.CharField(max_length=500, verbose_name='descrição'),
        ),
    ]
