# Generated by Django 5.1.5 on 2025-02-04 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifood', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtoifood',
            old_name='fd_grupo_catalogo_id',
            new_name='fd_grupo_catalog_id',
        ),
        migrations.RenameField(
            model_name='produtoifood',
            old_name='fd_item_catalogo_id',
            new_name='fd_item_catalog_id',
        ),
    ]
