# Generated by Django 5.1.3 on 2024-12-14 22:26

import django.db.models.deletion
import django_multitenant.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filiais', '0007_alter_filial_fl_catalog_id_and_more'),
        ('ifood', '0002_remove_categoriaifood_cd_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaifood',
            name='cd_filial',
            field=django_multitenant.fields.TenantForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dados_categorias_ifood', to='filiais.filial', verbose_name='filial'),
        ),
    ]
