# Generated by Django 5.1.5 on 2025-02-04 14:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assinaturas', '0003_initial'),
        ('filiais', '0003_rename_fl_catalogo_grupo_id_filial_fl_catalog_grupo_id_and_more'),
        ('ifood', '0003_rename_fd_grupo_catalogo_id_produtoifood_fd_grupo_catalog_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CatalogoIfood',
            new_name='CatalogIfood',
        ),
        migrations.AlterModelOptions(
            name='catalogifood',
            options={'ordering': ['-id'], 'verbose_name': 'Catálog do iFood', 'verbose_name_plural': 'Catálogs do iFood'},
        ),
        migrations.AlterModelTable(
            name='catalogifood',
            table='catalog_ifood',
        ),
    ]
