# Generated by Django 5.1.3 on 2024-12-15 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifood', '0003_categoriaifood_cd_filial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriaifood',
            name='cd_filial',
        ),
    ]
