# Generated by Django 5.1.4 on 2024-12-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifood', '0005_alter_produtoifood_fd_pizza_catalogoifood'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtoifood',
            name='fd_categoria_id',
            field=models.UUIDField(null=True, verbose_name='id do grupo do catálogo ifood'),
        ),
        migrations.AddField(
            model_name='produtoifood',
            name='fd_grupo_catalogo_id',
            field=models.UUIDField(null=True, verbose_name='id do grupo do catálogo ifood'),
        ),
        migrations.AddField(
            model_name='produtoifood',
            name='fd_index',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='posição no cardápio'),
        ),
        migrations.AddField(
            model_name='produtoifood',
            name='fd_item_catalog_id',
            field=models.UUIDField(null=True, verbose_name='id do item no catálogo ifood'),
        ),
        migrations.AlterField(
            model_name='produtoifood',
            name='fd_ifood_id',
            field=models.UUIDField(null=True, verbose_name='id ifood'),
        ),
    ]
