# Generated by Django 5.1.4 on 2024-12-26 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifood', '0006_produtoifood_fd_categoria_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtoifood',
            old_name='fd_item_catalog_id',
            new_name='fd_item_catalogo_id',
        ),
    ]
