# Generated by Django 5.1.5 on 2025-01-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifood', '0008_pedidoifood_pedidoitemifood_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoifood',
            name='fd_tipo_pedido',
        ),
        migrations.RemoveField(
            model_name='pedidoitemifood',
            name='ft_tipo_pedido',
        ),
        migrations.AddField(
            model_name='pedidoifood',
            name='fd_documento_cliente',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='documento do cliente'),
        ),
        migrations.AddField(
            model_name='pedidoifood',
            name='fd_nome_cliente',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='nome do cliente'),
        ),
        migrations.AddField(
            model_name='pedidoifood',
            name='fd_telefone_cliente',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='telefone do cliente'),
        ),
        migrations.AddField(
            model_name='pedidoitemifood',
            name='ft_index',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='index do item do pedido no iFood'),
        ),
        migrations.AlterField(
            model_name='pedidoitemifood',
            name='ft_preco_unitario',
            field=models.FloatField(default=0, verbose_name='preço unitário'),
        ),
        migrations.AlterField(
            model_name='pedidoitemifood',
            name='ft_quantidade',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='quantidade'),
        ),
    ]
