# Generated by Django 5.1.5 on 2025-01-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifood', '0009_remove_pedidoifood_fd_tipo_pedido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoitemcomplementoifood',
            name='pf_unidade',
        ),
        migrations.AddField(
            model_name='pedidoitemcomplementoifood',
            name='pf_tipo',
            field=models.CharField(default='', max_length=20, verbose_name='unidade'),
        ),
    ]
