# Generated by Django 5.1.5 on 2025-01-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifood', '0010_remove_pedidoitemcomplementoifood_pf_unidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoitemcomplementoifood',
            name='pf_nome',
            field=models.CharField(default='', verbose_name='nome'),
        ),
    ]
