# Generated by Django 5.1.5 on 2025-01-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifood', '0011_pedidoitemcomplementoifood_pf_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoifood',
            name='fd_complemento',
            field=models.CharField(blank=True, default='', max_length=350, verbose_name='complemento'),
        ),
    ]
