# Generated by Django 5.1.5 on 2025-01-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifood', '0012_alter_pedidoifood_fd_complemento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoitemifood',
            name='fd_imagem_produto',
            field=models.URLField(blank=True, default='', verbose_name='complemento'),
        ),
    ]
