# Generated by Django 5.1.5 on 2025-01-31 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifood', '0013_alter_pedidoitemifood_fd_imagem_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoitemcomplementoifood',
            name='pf_nome',
            field=models.CharField(default='', max_length=150, verbose_name='nome'),
        ),
    ]
