# Generated by Django 5.1.5 on 2025-01-31 19:36

import django.db.models.deletion
import django.db.models.manager
import django_lifecycle.mixins
import django_multitenant.mixins
import django_multitenant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assinaturas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('codigo', models.PositiveBigIntegerField(default=1, editable=False, verbose_name='código')),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='data de criação')),
                ('hora_criacao', models.TimeField(auto_now_add=True, verbose_name='hora de criação')),
                ('data_ultima_alteracao', models.DateField(auto_now=True, verbose_name='data da última alteração')),
                ('hora_ultima_alteracao', models.TimeField(auto_now=True, verbose_name='hora da última alteração')),
                ('cl_nome', models.CharField(max_length=30, verbose_name='nome')),
                ('cl_sobrenome', models.CharField(max_length=50, verbose_name='nome')),
                ('cl_nascimento', models.DateField(null=True, verbose_name='data de nascimento')),
                ('cl_celular', models.CharField(blank=True, max_length=11, verbose_name='celular')),
                ('cl_telefone', models.CharField(blank=True, max_length=10, verbose_name='telefone')),
                ('cl_email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('cl_cep', models.CharField(blank=True, default='', max_length=8, verbose_name='cep')),
                ('cl_estado', models.PositiveSmallIntegerField(choices=[(0, 'Em branco'), (1, 'Rondônia'), (2, 'Acre'), (3, 'Amazonas'), (4, 'Roraima'), (5, 'Pará'), (6, 'Amapá'), (7, 'Tocantins'), (8, 'Maranhão'), (9, 'Piauí'), (10, 'Ceará'), (11, 'Rio Grande do Norte'), (12, 'Paraíba'), (13, 'Pernambuco'), (14, 'Alagoas'), (15, 'Sergipe'), (16, 'Bahia'), (17, 'Minas Gerais'), (18, 'Espírito Santo'), (19, 'Rio de Janeiro'), (20, 'São Paulo'), (21, 'Paraná'), (22, 'Santa Catarina'), (23, 'Rio Grande do Sul'), (24, 'Mato Grosso do Sul'), (25, 'Mato Grosso'), (26, 'Goiás'), (27, 'Distrito Federal'), (28, 'Exterior')], default=0, verbose_name='estado')),
                ('cl_cidade', models.CharField(blank=True, default='', max_length=50, verbose_name='cidade')),
                ('cl_bairro', models.CharField(blank=True, default='', max_length=40, verbose_name='bairro')),
                ('cl_rua', models.CharField(blank=True, default='', max_length=30, verbose_name='rua')),
                ('cl_numero', models.CharField(blank=True, default='', max_length=8, verbose_name='número')),
                ('cl_complemento', models.CharField(blank=True, default='', max_length=100, verbose_name='complemento')),
                ('assinatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='assinaturas.assinatura', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
                'ordering': ['-id'],
            },
            bases=(django_multitenant.mixins.TenantModelMixin, django_lifecycle.mixins.LifecycleModelMixin, models.Model),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
    ]
