# Generated by Django 5.1.5 on 2025-01-31 19:36

import django.db.models.deletion
import django_multitenant.fields
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estoque', '0002_initial'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='mv_produto',
            field=django_multitenant.fields.TenantForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='produtos.produto', verbose_name='produto gerado'),
        ),
    ]
