# Generated by Django 5.1.5 on 2025-02-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='pr_imagem',
        ),
        migrations.AddField(
            model_name='produto',
            name='pr_id_back_blaze',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='foto'),
        ),
        migrations.AddField(
            model_name='produto',
            name='pr_path_imagem',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='foto'),
        ),
    ]
