# Generated by Django 5.1.3 on 2024-11-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='pr_imagem',
            field=models.URLField(blank=True, default='', verbose_name='foto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='pr_tipo',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Preparável'), (2, 'Consumível'), (3, 'Adicional')], default=2, verbose_name='tipo'),
        ),
    ]
