# Generated by Django 5.1.5 on 2025-02-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_remove_produto_pr_imagem_produto_pr_id_back_blaze_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='pr_url_imagem',
            field=models.URLField(blank=True, default='', verbose_name='url amigável da foto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='pr_id_back_blaze',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='id backblaze do upload'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='pr_path_imagem',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='caminho da imagem no bucket'),
        ),
    ]
