# Generated by Django 5.1.5 on 2025-02-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_produto_pr_url_imagem_alter_produto_pr_id_back_blaze_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='pr_ponto_carne',
            field=models.IntegerField(choices=[(0, 'Não tem ponto'), (1, 'Mal passada'), (2, 'Ao ponto para mal passada'), (3, 'Ao ponto'), (4, 'Ao ponto para bem passada'), (5, 'Bem passada')], default=0, verbose_name='ponto da carne'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='pr_quantidade',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='tipo'),
        ),
    ]
