# Generated by Django 5.1.3 on 2024-12-11 22:27

import django.db.models.deletion
import django.db.models.manager
import django_multitenant.fields
import django_multitenant.mixins
import django_multitenant.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filiais', '0005_filial_fl_merchat_id_ifood'),
        ('produtos', '0004_acrescimo_acrescimoproduto'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acrescimo',
            options={'ordering': ['-id'], 'verbose_name': 'Acréscimo do Produto', 'verbose_name_plural': 'Acréscimos dos Produtos'},
        ),
        migrations.AddField(
            model_name='acrescimo',
            name='cs_obrigatorio',
            field=models.BooleanField(default=False, verbose_name='obrigatório'),
        ),
        migrations.AddField(
            model_name='acrescimo',
            name='cs_quantidade_maxima',
            field=models.FloatField(default=1, verbose_name='quantidade máxima'),
        ),
        migrations.AddField(
            model_name='acrescimo',
            name='cs_quantidade_minima',
            field=models.FloatField(default=1, verbose_name='quantidade máxima'),
        ),
        migrations.AddField(
            model_name='produto',
            name='pr_organico',
            field=models.BooleanField(default=False, verbose_name='orgânico'),
        ),
        migrations.AddField(
            model_name='produto',
            name='pr_sem_acucar',
            field=models.BooleanField(default=False, verbose_name='sem açúcar'),
        ),
        migrations.AddField(
            model_name='produto',
            name='pr_sem_gluten',
            field=models.BooleanField(default=False, verbose_name='sem glúten'),
        ),
        migrations.AddField(
            model_name='produto',
            name='pr_vegano',
            field=models.BooleanField(default=False, verbose_name='vegano'),
        ),
        migrations.AddField(
            model_name='produto',
            name='pr_vegetariano',
            field=models.BooleanField(default=False, verbose_name='vegetariano'),
        ),
        migrations.AddField(
            model_name='produto',
            name='pr_zero_lactose',
            field=models.BooleanField(default=False, verbose_name='zero lactose'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='pr_tipo',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Preparável'), (2, 'Consumível')], default=2, verbose_name='tipo'),
        ),
        migrations.AlterModelTable(
            name='acrescimo',
            table='acresimo_produto',
        ),
        migrations.CreateModel(
            name='GrupoAcrescimoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('codigo', models.PositiveBigIntegerField(default=1, editable=False, verbose_name='código')),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='data de criação')),
                ('hora_criacao', models.TimeField(auto_now_add=True, verbose_name='hora de criação')),
                ('data_ultima_alteracao', models.DateField(auto_now=True, verbose_name='data da última alteração')),
                ('hora_ultima_alteracao', models.TimeField(auto_now=True, verbose_name='hora da última alteração')),
                ('gr_nome', models.CharField(max_length=30, verbose_name='nome')),
                ('ambiente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenants.ambiente', verbose_name='tenant')),
                ('filial', django_multitenant.fields.TenantForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='filiais.filial', verbose_name='filial')),
                ('owner', django_multitenant.fields.TenantForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'Grupo de Acréscimo do Produto',
                'verbose_name_plural': 'Grupos de Acréscimos dos Produtos',
                'db_table': 'grupo_acrescimo_produto',
                'ordering': ['-id'],
            },
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AddField(
            model_name='acrescimo',
            name='cs_grupo_acrescimo',
            field=django_multitenant.fields.TenantForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='acrescimos', to='produtos.grupoacrescimoproduto', verbose_name='grupo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='pr_grupo_acrescimo',
            field=django_multitenant.fields.TenantForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='produtos.grupoacrescimoproduto', verbose_name='garçom'),
        ),
        migrations.DeleteModel(
            name='AcrescimoProduto',
        ),
    ]
