# Generated by Django 5.1.5 on 2025-02-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_produto_pr_ponto_carne_alter_produto_pr_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='pr_id_back_blaze',
            field=models.CharField(blank=True, default='', max_length=102, verbose_name='id backblaze do upload'),
        ),
    ]
