# Generated by Django 5.1.4 on 2024-12-26 13:17

import django.db.models.deletion
import django_multitenant.fields
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filiais', '0008_filial_fl_hora_fim_funcionamento_domingo_and_more'),
        ('produtos', '0006_alter_categoriaproduto_cg_descricao'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GrupoAcrescimoProduto',
            new_name='GrupoComplementoProduto',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='pr_grupo_acrescimo',
        ),
        migrations.AddField(
            model_name='produto',
            name='pr_grupo_complementos',
            field=django_multitenant.fields.TenantForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='produtos.grupocomplementoproduto', verbose_name='grupo de complementos'),
        ),
    ]
