# Generated by Django 5.1.5 on 2025-02-17 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_alter_produto_pr_id_back_blaze'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='pr_ponto_carne',
        ),
    ]
