# Generated by Django 5.1.4 on 2024-12-26 13:29

import django.db.models.deletion
import django.db.models.manager
import django_lifecycle.mixins
import django_multitenant.fields
import django_multitenant.mixins
import django_multitenant.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filiais', '0008_filial_fl_hora_fim_funcionamento_domingo_and_more'),
        ('produtos', '0007_rename_grupoacrescimoproduto_grupocomplementoproduto_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelTable(
            name='grupocomplementoproduto',
            table='grupo_complemento_produto',
        ),
        migrations.CreateModel(
            name='ComplementoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('codigo', models.PositiveBigIntegerField(default=1, editable=False, verbose_name='código')),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='data de criação')),
                ('hora_criacao', models.TimeField(auto_now_add=True, verbose_name='hora de criação')),
                ('data_ultima_alteracao', models.DateField(auto_now=True, verbose_name='data da última alteração')),
                ('hora_ultima_alteracao', models.TimeField(auto_now=True, verbose_name='hora da última alteração')),
                ('pc_nome', models.CharField(max_length=40, verbose_name='nome')),
                ('pc_preco', models.FloatField(default=0, verbose_name='preço')),
                ('pc_quantidade_minima', models.FloatField(default=1, verbose_name='quantidade máxima')),
                ('pc_quantidade_maxima', models.FloatField(default=1, verbose_name='quantidade máxima')),
                ('pc_descricao', models.CharField(blank=True, max_length=50, verbose_name='descrição')),
                ('pc_obrigatorio', models.BooleanField(default=False, verbose_name='obrigatório')),
                ('ambiente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenants.ambiente', verbose_name='tenant')),
                ('filial', django_multitenant.fields.TenantForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='filiais.filial', verbose_name='filial')),
                ('owner', django_multitenant.fields.TenantForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('pc_grupo_complemento', django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complementos', to='produtos.grupocomplementoproduto', verbose_name='grupo de complemento')),
            ],
            options={
                'verbose_name': 'Complemento do Produto',
                'verbose_name_plural': 'Complementos dos Produtos',
                'db_table': 'complemento_produto',
                'ordering': ['-id'],
            },
            bases=(django_multitenant.mixins.TenantModelMixin, django_lifecycle.mixins.LifecycleModelMixin, models.Model),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.DeleteModel(
            name='Acrescimo',
        ),
    ]
