# Generated by Django 5.1.4 on 2024-12-26 13:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0008_alter_grupocomplementoproduto_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='pr_serve_pessoas',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(4)], verbose_name='n° de pessoas que a comida serve'),
        ),
    ]
