# Generated by Django 5.1.5 on 2025-06-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0008_remove_grupocomplementoproduto_assinatura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='pr_codigo_cardapio',
            field=models.CharField(blank=True, default='', max_length=8, verbose_name='código do cardápio'),
        ),
    ]
