# Generated by Django 5.1.4 on 2024-12-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0009_produto_pr_serve_pessoas'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='pr_quantidade',
            field=models.IntegerField(default=0, verbose_name='tipo'),
        ),
        migrations.AddField(
            model_name='produto',
            name='pr_unidade',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Grama'), (2, 'Quilo'), (3, 'Mililitro'), (4, 'Litro'), (5, 'Unidade'), (6, 'Fatia'), (7, 'Porção'), (99, 'Outra')], null=True, verbose_name='tipo'),
        ),
    ]
