# Generated by Django 5.1.4 on 2025-01-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usuario_filial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pendente'), (2, 'Aceito'), (3, 'Recusado')], default=1, verbose_name='status'),
        ),
    ]
