# Generated by Django 5.1.5 on 2025-01-28 19:30

import apps.users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usuario_status'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', apps.users.models.MultitenantUsuarioManager()),
                ('all_objects', apps.users.models.UsuarioManager()),
            ],
        ),
    ]
