# Generated by Django 5.1.5 on 2025-01-31 19:36

import apps.filas.mixins
import django.db.models.deletion
import django.db.models.manager
import django_lifecycle.mixins
import django_multitenant.mixins
import django_multitenant.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assinaturas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('codigo', models.PositiveBigIntegerField(default=1, editable=False, verbose_name='código')),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='data de criação')),
                ('hora_criacao', models.TimeField(auto_now_add=True, verbose_name='hora de criação')),
                ('data_ultima_alteracao', models.DateField(auto_now=True, verbose_name='data da última alteração')),
                ('hora_ultima_alteracao', models.TimeField(auto_now=True, verbose_name='hora da última alteração')),
                ('ff_uuid', models.UUIDField(default=uuid.uuid4, verbose_name='uuid')),
                ('ff_posicao', models.PositiveSmallIntegerField(default=1, verbose_name='posição')),
                ('ff_cliente', models.CharField(max_length=40, verbose_name='cliente')),
                ('ff_celular', models.CharField(max_length=11, verbose_name='telefone')),
                ('ff_quantidade_pessoas', models.PositiveSmallIntegerField(default=1, verbose_name='n° de pessoas')),
                ('ff_observacao', models.CharField(blank=True, default='', max_length=60, verbose_name='observação')),
                ('assinatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='assinaturas.assinatura', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'Fila',
                'verbose_name_plural': 'Filas',
                'db_table': 'fila',
                'ordering': ['-id'],
            },
            bases=(django_multitenant.mixins.TenantModelMixin, django_lifecycle.mixins.LifecycleModelMixin, models.Model, apps.filas.mixins.FilaHooksMixin),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
    ]
