# Generated by Django 5.1.3 on 2024-12-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fila',
            name='ff_observacao',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='cliente'),
        ),
    ]
