# Generated by Django 5.1.3 on 2024-12-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filas', '0002_alter_fila_ff_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fila',
            name='ff_observacao',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='observação'),
        ),
        migrations.AlterField(
            model_name='fila',
            name='ff_telefone',
            field=models.CharField(max_length=11, verbose_name='telefone'),
        ),
    ]
