# Generated by Django 5.1.4 on 2024-12-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filas', '0003_alter_fila_ff_observacao_alter_fila_ff_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='fila',
            name='ff_quantidade_pessoas',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='n° de pessoas'),
        ),
    ]
