# Generated by Django 5.1.4 on 2024-12-23 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filas', '0004_fila_ff_quantidade_pessoas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fila',
            old_name='ff_telefone',
            new_name='ff_celular',
        ),
    ]
