# Generated by Django 5.1.4 on 2024-12-23 19:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filas', '0005_rename_ff_telefone_fila_ff_celular'),
    ]

    operations = [
        migrations.AddField(
            model_name='fila',
            name='ff_uuid',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='uuid'),
        ),
    ]
