# Generated by Django 5.1.5 on 2025-02-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assinaturas', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plano',
            name='pl_limite_integracoes_ifood',
        ),
        migrations.AddField(
            model_name='plano',
            name='pl_integra_ifood',
            field=models.BooleanField(default=False, verbose_name='define se o plano inegra com o ifood'),
        ),
        migrations.AddField(
            model_name='plano',
            name='pl_limite_integracoes_pedidos_ifood',
            field=models.PositiveIntegerField(default=0, verbose_name='número máximo pedidos de ifood recebíveis'),
        ),
        migrations.AddField(
            model_name='plano',
            name='pl_numero_telas',
            field=models.PositiveIntegerField(default=1, verbose_name='número de telas'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='pl_numero_usuarios',
            field=models.PositiveIntegerField(default=2, verbose_name='número usuarios'),
        ),
    ]
