# Generated by Django 5.1.5 on 2025-06-28 16:14

import django.db.models.deletion
import django_multitenant.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assinaturas', '0004_remove_plano_pl_limite_integracoes_ifood_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='plano',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='plano',
            name='assinatura',
        ),
        migrations.RemoveField(
            model_name='plano',
            name='filial',
        ),
        migrations.RemoveField(
            model_name='plano',
            name='owner',
        ),
        migrations.AddField(
            model_name='assinatura',
            name='ss_plano',
            field=django_multitenant.fields.TenantForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='assinaturas.plano', verbose_name='plano'),
            preserve_default=False,
        ),
    ]
