# Generated by Django 5.2.1 on 2025-05-30 00:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import django_multitenant.fields


class Migration(migrations.Migration):

    dependencies = [
        ('assinaturas', '0004_remove_plano_pl_limite_integracoes_ifood_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plano',
            name='assinatura',
        ),
        migrations.RemoveField(
            model_name='plano',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='plano',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='plano',
            name='filial',
        ),
        migrations.RemoveField(
            model_name='plano',
            name='owner',
        ),
        migrations.AddField(
            model_name='assinatura',
            name='data_criacao',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='data de criação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assinatura',
            name='data_ultima_alteracao',
            field=models.DateField(auto_now=True, verbose_name='data da última alteração'),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='hora_criacao',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='hora de criação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assinatura',
            name='hora_ultima_alteracao',
            field=models.TimeField(auto_now=True, verbose_name='hora da última alteração'),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='ss_plano',
            field=django_multitenant.fields.TenantForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='assinaturas', to='assinaturas.plano', verbose_name='plano'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plano',
            name='pl_envia_sms',
            field=models.BooleanField(default=False, verbose_name='envia sms'),
        ),
        migrations.AddField(
            model_name='plano',
            name='pl_limite_sms',
            field=models.PositiveIntegerField(default=0, verbose_name='número máximo sms por mês'),
        ),
        migrations.AddField(
            model_name='plano',
            name='pl_saldo_sms',
            field=models.PositiveIntegerField(default=0, verbose_name='saldo restante dos sms por mês'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='pl_integra_ifood',
            field=models.BooleanField(default=False, verbose_name='integra com o ifood'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='pl_limite_integracoes_pedidos_ifood',
            field=models.PositiveIntegerField(default=0, verbose_name='número máximo pedidos de ifood recebíveis por mês'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='pl_observacao',
            field=models.CharField(max_length=50, verbose_name='observações'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='pl_valor_mensalidade',
            field=models.FloatField(default=0, verbose_name='valor da mensalidade'),
        ),
    ]
