# Generated by Django 5.2.3 on 2025-06-28 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assinaturas', '0005_alter_plano_managers_remove_plano_assinatura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assinatura',
            name='ss_plano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assinaturas.plano', verbose_name='plano'),
        ),
    ]
