# Generated by Django 5.1.3 on 2024-11-14 20:09

import django.db.models.deletion
import django_multitenant.fields
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('comandas', '0001_initial'),
        ('descontos', '0001_initial'),
        ('fidelidade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comanda',
            name='cm_cartao_fidelidade',
            field=django_multitenant.fields.TenantForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='fidelidade.cartaofidelidade', verbose_name='cartão fidelidade resgatado'),
        ),
        migrations.AddField(
            model_name='comanda',
            name='cm_cliente_fidelidade',
            field=django_multitenant.fields.TenantForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente', verbose_name='cliente fidelidade'),
        ),
        migrations.AddField(
            model_name='comanda',
            name='cm_cupon',
            field=django_multitenant.fields.TenantForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='descontos.cupondesconto', verbose_name='cupon'),
        ),
    ]
