# Generated by Django 5.1.3 on 2024-11-14 20:09

import django.db.models.deletion
import django_multitenant.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comandas', '0002_initial'),
        ('filiais', '0001_initial'),
        ('mesas', '0001_initial'),
        ('produtos', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comanda',
            name='cm_garcom',
            field=django_multitenant.fields.TenantForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comandas', to=settings.AUTH_USER_MODEL, verbose_name='garçom'),
        ),
        migrations.AddField(
            model_name='comanda',
            name='cm_mesa',
            field=django_multitenant.fields.TenantForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comandas', to='mesas.mesa', verbose_name='mesa'),
        ),
        migrations.AddField(
            model_name='comanda',
            name='filial',
            field=django_multitenant.fields.TenantForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='filiais.filial', verbose_name='filial'),
        ),
        migrations.AddField(
            model_name='comanda',
            name='owner',
            field=django_multitenant.fields.TenantForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AddField(
            model_name='comandaitem',
            name='ambiente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenants.ambiente', verbose_name='tenant'),
        ),
        migrations.AddField(
            model_name='comandaitem',
            name='ct_comanda',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='comandas.comanda', verbose_name='comanda'),
        ),
        migrations.AddField(
            model_name='comandaitem',
            name='ct_produto',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comanda_itens', to='produtos.produto', verbose_name='produto'),
        ),
        migrations.AddField(
            model_name='comandaitem',
            name='filial',
            field=django_multitenant.fields.TenantForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='filiais.filial', verbose_name='filial'),
        ),
        migrations.AddField(
            model_name='comandaitem',
            name='owner',
            field=django_multitenant.fields.TenantForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
    ]
